config/routes.rb
Openaidregister::Application.routes.draw do

  resources :users do
    resources :projects
    resources :organizations do
      resources :budgets
      resources :documents
      resources :administrators
    end
  end

  resources :sessions

  resources :projects do
    resources :transactions
    resources :external_organizations
    resources :documents
    resources :project_results
  end

  root :to     => 'home#index'
  get '/faq'   => 'home#faq'
  get '/about' => 'home#about'
  get '/terms' => 'home#terms'

end

app/models/user.rb
class User < CartodbModel

  attr_accessor :email,
                :password,
                :name,
                :organization_id

  validates :email, :presence => true, :email => true
  validates :password, :presence => true
  validate :email_uniqueness

  def self.with_credentials(email, password)
    User.where(:email => email, :password => password).first
  end

  def self.find_by_name(name)
    User.where(:name => name).first
  end

  def projects
    Project.for_user(cartodb_id)
  end

  def save
    if self.valid?
      if organization && organization.valid?
        attributes['organization_id'] = organization.save.cartodb_id
        super
      end
    end

    self
  end

  def organization
    @organization ||= Organization.find_by_id(@organization_id)
  end

  def organization=(organization_attributes)
    @organization = if organization_attributes.is_a?(Organization)
                      organization_attributes
                    else
                      Organization.new(organization_attributes)
                    end
  end

  private

  def email_uniqueness
    return true if persisted?

    if User.where(:email => email).length > 0
      errors.add :email,    'already exists'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :login_required, :only => [:new, :create]

  def show
    @projects = current_user.projects
  end

  def new
    @user               = User.new
    @user.organization  = Organization.new
    @organization_types = OpenAidRegister::ORGANIZATION_TYPES
    @countries          = OpenAidRegister::COUNTRIES
  end

  def create
    @user = User.new(params[:user])

    if @user.save

      warden.set_user(@user)

      flash[:info] = new_project_path
      redirect_to @user
    else
      @organization_types = OpenAidRegister::ORGANIZATION_TYPES
      @countries          = OpenAidRegister::COUNTRIES
      render :new
    end
  end

  def edit
    @user               = current_user
    @user.organization  ||= Organization.new
    @organization_types = OpenAidRegister::ORGANIZATION_TYPES
    @countries          = OpenAidRegister::COUNTRIES

    render :layout => false
  end

  def update
    @user = current_user

    if @user.update_attributes(params[:user])

      redirect_to @user
    else
      @user.organization  ||= Organization.new
      @organization_types = OpenAidRegister::ORGANIZATION_TYPES
      @countries          = OpenAidRegister::COUNTRIES
      render :edit
    end
  end
end

app/views/users/_header.html.erb
<div class="inner">
  <section class="light borders bottom">
    <header>
      <h1 class="left"><%= link_to t('title_for_html'), "/" %></h1>
      <nav class="right">
        <%= link_to t('header.home'),           "/",                                :class => 'upper bold small' %>
        <!--<%= link_to t('header.organizations'),  "#",                            :class => 'upper bold small' %>-->
        <%= link_to t('header.blog'),           'http://blog.openaidregister.org',  :class => 'upper bold small' %>
        <%= link_to t('header.about'),          about_path,                         :class => 'upper bold small' %>
        <span class="user_options">
          <%= link_to t('header.dashboard'),    user_path(current_user),            :class => 'upper bold small' %>
          <%= link_to t('header.your_profile'), edit_user_path(current_user),       :class => 'upper bold small profile' %>
          <%= button_to "logout",               session_path(current_user),         :method => :delete, :class => '' %>
        </span>
      </nav>
    </header>
  </section>
</div>

app/views/users/edit.html.erb
<%= javascript_include_tag :edit_users if request.xhr? %>

<div class="form_inner edit_user">
  <section>
    <div>
      <h3 class="center upper"><span class="title_line"></span><%= t('.profile') %><span class="title_line"></span></h3>
    </div>
  </section>

  <section class="header borders">
    <div class="center">
      <%= link_to t('.account_data'), "#account_data", :class => "selected button round white account_data uppercase" %>
      <%= link_to t('.organization_data'), "#organization_data", :class => "button round white organization_data uppercase" %>
    </div>
  </section>

  <section class="edit_user_forms">
    <div class="form_wrapper">
      <%= form_for(@user) do |f| %>
        <div class="user">
          <div class="name field">
            <%= error_message(@user, :name) %>
            <%= f.label :name, t('.name') %>
            <%= f.text_field :name, :autofocus => true, :class => "med" %>
          </div>

          <div class="email field margin25">
            <%= error_message(@user, :email) %>
            <%= f.label :email, t('.email') %>
            <%= f.email_field :email, :class => "med" %>
          </div>

          <div class="password field margin margin25">
            <%= f.label :password, t('.password') %>
            <%= error_message(@user, :password) %>
            <%= f.password_field :password, :class => "short" %>
          </div>

          <div class="field margin50">
            <%= f.button t('.save_changes'), :type => 'submit', :class => "red round button bigger save" %>
          </div>
        </div>
      <% end %>
    </div>

    <%= form_for(@user) do |f| %>
      <div class="organization">
        
        <%= f.fields_for @user.organization do |ff| %>

          <div class="form_wrapper">
            <div class="organization_name field">
              <%= error_message(@user, :name) %>
              <%= ff.label :name, t('.organization.name') %>
              <%= ff.text_field :name, :class => "med" %>
            </div>

            <div class="organization_website field margin">
              <%= error_message(@user, :website) %>
              <%= ff.label :website, t('.organization.website') %>
              <%= ff.text_field :website, :class => "short" %>
            </div>

            <div class="organization_type_id field short margin20">
              <%= error_message(@user, :type_id) %>
              <%= ff.label :type_id, t('.organization.type_id') %>
              <div class="select_wrapper">
                <%= ff.select :type_id, to_select_options(@organization_types), { :include_blank => true }, { 'data-placeholder' => "Not defined..." } %>
              </div>
            </div>

            <div class="organization_country_id field margin20 margin med">
              <%= error_message(@user, :country_id) %>
              <%= ff.label :country_id, t('.organization.country_id') %>
              <div class="select_wrapper">
                <%= ff.select :country_id, to_select_options(@countries), { :include_blank => true }, { 'data-placeholder' => "Not defined..." } %>
              </div>
            </div>

            <div class="organization_government_id field margin20">
              <%= error_message(@user, :government_id) %>
              <div class="block">
                <%= ff.label :government_id, t('.organization.government_id.title'), :class => "with_hint" %>
                <span class="hint"
                  data-title="<%= t('.organization.government_id.title') %>"
                  data-description="<%= t('.organization.government_id.desc') %>"
                  data-url="<%= t('.organization.government_id.url') %>"
                  data-examples="<%= t('.organization.government_id.examples') %>"></span>
              </div>
              <%= ff.text_field :government_id, :class => "short" %>
            </div>
          </div>

          <% if @user.organization.persisted? %>
            <section class="form_center border">
              <div class="form_wrapper">

                <div class="field long budget">
                  <div class="block">
                    <label class="with_hint"><%= t('.organization.budgets.title') %></label>
                    <span class="hint"
                      data-title="<%= t('.organization.budgets.title') %>"
                      data-description="<%= t('.organization.budgets.desc') %>"
                      data-url="<%= t('.organization.budgets.url') %>"
                      data-examples="<%= t('.organization.budgets.examples') %>"></span>
                  </div>
                  <div class="subform">
                    <ul class="results">
                      <%= list_for_collection(@user.organization.budgets) do %>
                        <li class="empty"><%= t('.organization.budgets.no_records') %></li>
                      <% end %>
                    </ul>
                    <div class="form"></div>
                    <%= link_to t('.organization.add'), new_user_organization_budget_path(@user, @user.organization), :class => 'round grey button upper add_form margin10' %>
                  </div>
                </div>

                <div class="field long documents margin50">
                  <div class="block">
                    <label class="with_hint"><%= t('.organization.documents.title') %></label>
                    <span class="hint"
                      data-title="<%= t('.organization.documents.title') %>"
                      data-description="<%= t('.organization.documents.desc') %>"
                      data-url="<%= t('.organization.documents.url') %>"
                      data-examples="<%= t('.organization.documents.examples') %>"></span>
                  </div>
                  <div class="subform">
                    <ul class="results">
                      <%= list_for_collection(@user.organization.documents) do %>
                        <li class="empty"><%= t('.organization.documents.no_records') %></li>
                      <% end %>
                    </ul>
                    <div class="form"></div>
                    <%= link_to t('.organization.add'), new_user_organization_document_path(@user, @user.organization), :class => 'round grey button upper add_form margin10' %>
                  </div>
                </div>

              </div>
            </section>

            <section class="form_center border">
              <div class="form_wrapper">
                <div class="field long administrators">
                  <div class="block"> 
                    <label class="with_hint"><%= t('.organization.administrators.title') %></label>
                    <span class="hint"
                      data-title="<%= t('.organization.administrators.title') %>"
                      data-description="<%= t('.organization.administrators.desc') %>"
                      data-url="<%= t('.organization.administrators.url') %>"
                      data-examples="<%= t('.organization.administrators.examples') %>"></span>
                  </div>
                  <div class="subform">
                    <ul class="results">
                      <%= list_for_collection(@user.organization.administrators) do %>
                        <li class="empty"><%= t('.organization.administrators.no_records') %></li>
                      <% end %>
                    </ul>
                    <div class="form"></div>
                    <%= link_to t('.organization.add'), new_user_organization_administrator_path(@user, @user.organization), :class => 'round grey button upper add_form margin10' %>
                  </div>
                </div>
              </div>
            </section>
          <% end %>
        <% end %>

        <div class="form_wrapper">
          <div class="field block margin50">
            <%= f.submit t('.save_changes'), :class => "red round bigger save button" %>
          </div>
        </div>
        
      </div>
    <% end %>
  </section>
</div>

app/views/users/new.html.erb
<% content_for(:page_title) do %>OpenAidRegister | Sign up<% end %>

<%= content_for(:extra_assets) do %>
  <%= stylesheet_link_tag :sessions, :media => 'all' %>
  <script type="text/javascript">var newProjectFormPath;</script>
<% end %>

<div class="bkg"><div class="mesh"></div></div>

<div class="inner">
  <h1 class="center margin60"><%= link_to t('title_for_html'), "/" %></h1>

  <section class="sessions med">
    <h3 class="center block upper darker"><span class="title_line"></span><%= t('.create_your_account') %><span class="title_line"></span></h3>

    <%= form_for(@user) do |f| %>
      <div class="progress margin40">
        <div class="progress_bar">
          <span class="bar"></span>
        </div>
      </div>

      <div class="signup">
        <div class="user margin50">
          <div class="name field">
            <%= error_message(@user, :name) %>
            <%= f.label :name, t('.name') %>
            <%= f.text_field :name, :autofocus => true, :class => "med" %>
          </div>

          <div class="email field margin25">
            <%= error_message(@user, :email) %>
            <%= f.label :email, t('.email') %>
            <%= f.email_field :email, :class => "med" %>
          </div>

          <div class="password field margin margin25">

            <%= f.label :password, t('.password') %>
            <%= error_message(@user, :password) %>
            <%= f.password_field :password, :class => "short" %>
          </div>

          <div class="field margin50">
            <%= f.button t('.continue'), :type => 'button', :class => "red round button bigger continue" %>
          </div>
        </div>

        <div class="organization margin50">
          <%= f.fields_for @user.organization do |ff| %>
            <div class="organization_name field">
              <%= error_message(@user, :name) %>
              <%= ff.label :name, t('.organization.name') %>
              <%= ff.text_field :name, :class => "med" %>
            </div>

            <div class="organization_website field margin">
              <%= error_message(@user, :website) %>
              <%= ff.label :website, t('.organization.website') %>
              <%= ff.text_field :website, :class => "short" %>
            </div>

            <div class="organization_type_id field short margin20">
              <%= error_message(@user, :type_id) %>
              <%= ff.label :type_id, t('.organization.type_id') %>
              <div class="select_wrapper">
                <%= ff.select :type_id, to_select_options(@organization_types), { :include_blank => true }, { 'data-placeholder' => "Not defined..." } %>
              </div>
            </div>

            <div class="organization_country_id field margin20 margin med">
              <%= error_message(@user, :country_id) %>
              <%= ff.label :country_id, t('.organization.country_id') %>
              <div class="select_wrapper med">
                <%= ff.select :country_id, to_select_options(@countries), { :include_blank => true }, { 'data-placeholder' => "Not defined..." } %>
              </div>
            </div>

            <div class="organization_government_id field margin20">
              <%= error_message(@user, :government_id) %>
              <div class="block">
                <%= ff.label :government_id, t('.organization.government_id.title'), :class => "with_hint" %>
                <span class="hint"
                  data-title="<%= t('.organization.government_id.title') %>"
                  data-description="<%= t('.organization.government_id.desc') %>"
                  data-url="<%= t('.organization.government_id.url') %>"
                  data-examples="<%= t('.organization.government_id.examples') %>"></span>
              </div>
              <%= ff.text_field :government_id, :class => "short" %>
            </div>
          <% end %>

          <div class="field block margin40">
            <%= f.submit t('.save'), :class => "red round button bigger" %>
          </div>
        </div>
      </div>
    <% end %>

  </section>
</div>

<%= render :partial => 'layouts/sessions_footer' %>

app/views/users/show.html.erb
<% content_for(:page_title) do %>OpenAidRegister | <%= current_user.name %><% end %>

<script type="text/javascript">
  var newProjectFormPath = <% if flash[:info] %>'<%= flash[:info] %>'<% else %>false<% end %>;
</script>

<%= render :partial => 'header' %>

<!-- edit tools -->
<div class="inner">
  <section class="compact borders tools">
    <%= link_to t('users.publish.add_new_project'), new_project_path, :class => 'left button uppercase round red small new' %>
    <div class="publishing-tools right">
      <label class="small dark left"><%= t('users.publish.publishing_tools') %></label>
      <%= link_to t('users.publish.export'), '#', :class => 'button uppercase round white small left export' %>
      <%= link_to t('users.publish.share'), user_projects_path(current_user), :class => 'button uppercase round white small left share' %>
    </div>
  </section>
</div>

<!-- map -->
<section class="top bottom map">
  <div id="projects_map"></div>
  <div id="zoom"><a class="zoom_in">+</a><a class="zoom_out">-</a></div>
  <div class="empty_map">
    <p class="darker center bold bigger left"><%= t('users.map.empty.title') %></p>
    <p class="center left margin15"><%= link_to t('users.map.empty.button'), new_project_path, :class => "button red round new" %></p>
  </div>
</section>

<!-- list -->
<div class="inner list">
  <section class="borders bottom compact list_filters">
    <form class="search-form">
      <div class="field med">
        <input type="text" placeholder="<%= t('users.filters.search', :projects => @projects.size) %>"id="projects_search" />
      </div>
      <div class="right filter_selector">
        <label class="dark small left"><%= t('users.filters.label') %></label>

        <div class="field">
          <div class="select_wrapper">
          <select>
            <option>All</option>
            <option>Implementing</option>
            <option>Pipeline</option>
            <option>Completion</option>
          </select>
          </div>
        </div>

        <!-- <a href="#" class="selected uppercase button round white small left"><%= t('users.filters.all') %></a>
        <a href="#ongoing" class="button uppercase round white small left"><%= t('users.filters.ongoing') %></a>
        <a href="#past" class="button uppercase round white small left"><%= t('users.filters.past') %></a> -->
      </div>
    </form>
  </section>
  <section class="borders bottom list">
    <ul id="projects_list">
      <% @projects.each do |project| %>
        <li id="project_<%= project.cartodb_id %>" data-positions="<%= project.coords.to_json.html_safe %>">
          <p class="name"><%= link_to project.name, edit_project_path(project) %></p>
          <p class="status <%= project.state.last.downcase %>"><%= project.state.last %></p>
          <%= button_to "x", project_path(project), :method =>:delete %>
        </li>
      <% end %>
    </ul>
  </section>
</div>
<%= render :partial => 'layouts/footer' %>