config/routes.rb
Openaidregister::Application.routes.draw do

  resources :users do
    resources :projects
    resources :organizations do
      resources :budgets
      resources :documents
      resources :administrators
    end
  end

  resources :sessions

  resources :projects do
    resources :transactions
    resources :external_organizations
    resources :documents
    resources :project_results
  end

  root :to     => 'home#index'
  get '/faq'   => 'home#faq'
  get '/about' => 'home#about'
  get '/terms' => 'home#terms'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :login_required
end

app/views/home/_header.html.erb
<header>
  <h1 class="left"><%= link_to t('title_for_html'), "/" %></h1>
  <nav class="right">
    <%= link_to t('header.home'),               "/", :class => 'upper bold small' %>
    <!--<%= link_to t('header.organizations'),  "#", :class => 'upper bold small' %>-->
    <%= link_to t('header.blog'),               'http://blog.openaidregister.org', :class => 'upper bold small' %>
    <%= link_to t('header.about'),              about_path, :class => 'upper bold small' %>
    <% if current_user %>
      <%= link_to t('header.dashboard'),        user_path(current_user), :class => 'upper bold small round' %>
    <% else %>
      <%= link_to t('header.sign_in'),          new_session_path, :class => 'upper bold small round' %>
    <% end %>
  </nav>
</header>

app/views/home/about.html.erb
<% content_for(:page_title) do %>OpenAidRegister | About<% end %>

<!-- Intro -->
<section class="bkg">
  <div class="mesh">
    <div class="inner">
      <%= render :partial => 'header' %>
    </div>
  </div>
</section>

<div class="inner">
  <!-- EXAMPLE OF TWO COLUMNS EXPLANATION -->
  <section class="borders">
    <h3 class="center block upper darker"><span class="title_line"></span><%= t('index.goal.title') %><span class="title_line"></span></h3>
    <div class="columns margin45">
      <div class="column2">
        <p class="big dark"><%= t('index.goal.p1') %></p>
      </div>
      <div class="column2">
        <p class="big dark"><%= t('index.goal.p2') %></p>
      </div>
    </div>
  </section>
</div>


<section class="grey_section">
  <div class="inner">
    <section class="borders">
      <h3 class="center block upper dark"><span class="title_line"></span><%= t('index.using') %><span class="title_line"></span></h3>
      <div class="using_it">
        <%= link_to image_tag("logos/publish.png", :border=>0),           "http://www.publishwhatyoufund.org/", :target => "_blank" %>
        <%= link_to image_tag("logos/engineers.png", :border=>0),         "http://www.ewb.ca/",                 :target => "_blank" %>
        <%= link_to image_tag("logos/global_integrity.png", :border=>0),  "http://www.globalintegrity.org/",    :target => "_blank" %>
        <%= link_to image_tag("logos/indigo.png", :border=>0),            "http://indigotrust.wordpress.com/",  :target => "_blank" %>
        <%= link_to image_tag("logos/alliance.png", :border=>0),          "http://www.aidsalliance.org/",       :target => "_blank" %>
      </div>
    </section>
  </div>
</section>

<!-- Transparent -->
<section class="transparent center">
  <%= link_to t('index.transparent'), new_user_path, :class => "bold bigger title" %>
</section>

<%= render :partial => 'layouts/footer' %>

app/views/home/faq.html.erb
<% content_for(:page_title) do %>OpenAidRegister | FAQ<% end %>

<!-- Intro -->
<section class="bkg">
  <div class="mesh">
    <div class="inner">
      <%= render :partial => 'header' %>
    </div>
  </div>
</section>

<div class="inner">
  <!-- EXAMPLE OF TWO COLUMNS EXPLANATION -->
  <section class="borders">
    <h3 class="center block upper darker"><span class="title_line"></span><%= t('index.goal.title') %><span class="title_line"></span></h3>
    <div class="columns margin45">
      <div class="column2">
        <p class="big dark"><%= t('index.goal.p1') %></p>
      </div>
      <div class="column2">
        <p class="big dark"><%= t('index.goal.p2') %></p>
      </div>
    </div>
  </section>
</div>


<section class="grey_section">
  <div class="inner">
    <section class="borders">
      <h3 class="center block upper dark"><span class="title_line"></span><%= t('index.using') %><span class="title_line"></span></h3>
      <div class="using_it">
        <%= link_to image_tag("logos/publish.png", :border=>0),           "http://www.publishwhatyoufund.org/", :target => "_blank" %>
        <%= link_to image_tag("logos/engineers.png", :border=>0),         "http://www.ewb.ca/",                 :target => "_blank" %>
        <%= link_to image_tag("logos/global_integrity.png", :border=>0),  "http://www.globalintegrity.org/",    :target => "_blank" %>
        <%= link_to image_tag("logos/indigo.png", :border=>0),            "http://indigotrust.wordpress.com/",  :target => "_blank" %>
        <%= link_to image_tag("logos/alliance.png", :border=>0),          "http://www.aidsalliance.org/",       :target => "_blank" %>
      </div>
    </section>
  </div>
</section>

<!-- Transparent -->
<section class="transparent center">
  <%= link_to t('index.transparent'), new_user_path, :class => "bold bigger title" %>
</section>

<%= render :partial => 'layouts/footer' %>

app/views/home/index.html.erb
<% content_for(:page_title) do %>OpenAidRegister<% end %>

<!-- Intro -->
<section class="bkg">
  <div class="mesh">
    <div class="inner">
      <%= render :partial => 'header' %>
      <div class="banner">
        <h2 class="dark"><%= t('index.banner.title') %></h2>
        <%= link_to t('index.banner.link'), new_user_path, :class => "title bold bigger" %>
      </div>
    </div>
  </div>
</section>

<div class="inner">

  <!-- Goals -->
  <section class="borders">
    <h3 class="center block upper darker"><span class="title_line"></span><%= t('index.goal.title') %><span class="title_line"></span></h3>
    <div class="columns margin45">
      <div class="column2">
        <p class="big dark"><%= t('index.goal.p1') %></p>
      </div>
      <div class="column2">
        <p class="big dark"><%= t('index.goal.p2') %></p>
      </div>
    </div>
  </section>

  <!-- Video -->
  <section class="video">
    <div class="play">
      <%= link_to "", "#", :class => "play" %>
    </div>
    <div class="share">
      <h4><%= t('index.video.title') %></h4>
      <p class="big"><%= t('index.video.content') %></p>
      <div class="social margin25">
        <%= link_to t('index.video.twitter'), "#", :class => "twitter" %>
        <%= link_to t('index.video.facebook'), "#", :class => "facebook" %>
      </div>
    </div>
  </section>

  <!-- Recent_projects -->
  <section class="recent_projects borders">
    <h3 class="center block upper darker"><span class="title_line"></span><%= t('index.recent_projects.title') %><span class="title_line"></span></h3>
    <div class="columns margin40">
      <div class="column3">
        <h5><%= link_to t('index.recent_projects.p1.title'), '#', :class => "bigger" %></h5>
        <span class="info margin20">
          <p class="left lighter">Global Integrity</p>
          <p class="right lighter">21500 USD</p>
        </span>
        <p class="margin20"><%= t('index.recent_projects.p1.content') %></p>
        <span class="dates">
          <p class="smaller lighter start">2008</p>
          <span class="line"></span>
          <p class="smaller lighter end">2011</p>
        </span>
      </div>
      <div class="column3">
        <h5><%= link_to t('index.recent_projects.p1.title'), '#', :class => "bigger" %></h5>
        <span class="info margin20">
          <p class="left lighter">Global Integrity</p>
          <p class="right lighter">21500 USD</p>
        </span>
        <p class="margin20"><%= t('index.recent_projects.p1.content') %></p>
        <span class="dates">
          <p class="smaller lighter start">2008</p>
          <span class="line"></span>
          <p class="smaller lighter end">2011</p>
        </span>
      </div>
      <div class="column3">
        <h5><%= link_to t('index.recent_projects.p1.title'), '#', :class => "bigger" %></h5>
        <span class="info margin20">
          <p class="left lighter">Global Integrity</p>
          <p class="right lighter">21500 USD</p>
        </span>
        <p class="margin20"><%= t('index.recent_projects.p1.content') %></p>
        <span class="dates">
          <p class="smaller lighter start">2008</p>
          <span class="line break"></span>
          <p class="smaller lighter end">2016</p>
        </span>
      </div>
    </div>
  </section>
</div>

<!-- Already using OpenAidRegister -->
<section class="grey_section">
  <div class="inner">
    <section class="borders">
      <h3 class="center block upper dark"><span class="title_line"></span><%= t('index.using') %><span class="title_line"></span></h3>
      <div class="using_it">
        <%= link_to image_tag("logos/publish.png", :border=>0),           "http://www.publishwhatyoufund.org/", :target => "_blank" %>
        <%= link_to image_tag("logos/engineers.png", :border=>0),         "http://www.ewb.ca/",                 :target => "_blank" %>
        <%= link_to image_tag("logos/global_integrity.png", :border=>0),  "http://www.globalintegrity.org/",    :target => "_blank" %>
        <%= link_to image_tag("logos/indigo.png", :border=>0),            "http://indigotrust.wordpress.com/",  :target => "_blank" %>
        <%= link_to image_tag("logos/alliance.png", :border=>0),          "http://www.aidsalliance.org/",       :target => "_blank" %>
      </div>
    </section>
  </div>
</section>

<!-- Transparent -->
<section class="transparent center">
  <%= link_to t('index.transparent'), new_user_path, :class => "bold bigger title" %>
</section>

<%= render :partial => 'layouts/footer' %>

app/views/home/terms.html.erb
<% content_for(:page_title) do %>OpenAidRegister | Terms<% end %>

<!-- Intro -->
<section class="bkg">
  <div class="mesh">
    <div class="inner">
      <%= render :partial => 'header' %>
    </div>
  </div>
</section>

<div class="inner">
  <!-- EXAMPLE OF TWO COLUMNS EXPLANATION -->
  <section class="borders">
    <h3 class="center block upper darker"><span class="title_line"></span><%= t('index.goal.title') %><span class="title_line"></span></h3>
    <div class="columns margin45">
      <div class="column2">
        <p class="big dark"><%= t('index.goal.p1') %></p>
      </div>
      <div class="column2">
        <p class="big dark"><%= t('index.goal.p2') %></p>
      </div>
    </div>
  </section>
</div>


<section class="grey_section">
  <div class="inner">
    <section class="borders">
      <h3 class="center block upper dark"><span class="title_line"></span><%= t('index.using') %><span class="title_line"></span></h3>
      <div class="using_it">
        <%= link_to image_tag("logos/publish.png", :border=>0),           "http://www.publishwhatyoufund.org/", :target => "_blank" %>
        <%= link_to image_tag("logos/engineers.png", :border=>0),         "http://www.ewb.ca/",                 :target => "_blank" %>
        <%= link_to image_tag("logos/global_integrity.png", :border=>0),  "http://www.globalintegrity.org/",    :target => "_blank" %>
        <%= link_to image_tag("logos/indigo.png", :border=>0),            "http://indigotrust.wordpress.com/",  :target => "_blank" %>
        <%= link_to image_tag("logos/alliance.png", :border=>0),          "http://www.aidsalliance.org/",       :target => "_blank" %>
      </div>
    </section>
  </div>
</section>

<!-- Transparent -->
<section class="transparent center">
  <%= link_to t('index.transparent'), new_user_path, :class => "bold bigger title" %>
</section>

<%= render :partial => 'layouts/footer' %>