config/routes.rb
Openaidregister::Application.routes.draw do

  resources :users do
    resources :projects
    resources :organizations do
      resources :budgets
      resources :documents
      resources :administrators
    end
  end

  resources :sessions

  resources :projects do
    resources :transactions
    resources :external_organizations
    resources :documents
    resources :project_results
  end

  root :to     => 'home#index'
  get '/faq'   => 'home#faq'
  get '/about' => 'home#about'
  get '/terms' => 'home#terms'

end

app/models/project.rb
class Project < CartodbModel

  attr_accessor :user_id,
                :name,
                :id_in_organization,
                :description,
                :organization_role_id,
                :language_id,
                :sectors,
                :subsectors,
                :start_date,
                :end_date,
                :budget,
                :budget_currency_id,
                :contact_person,
                :collaboration_type,
                :tied_status,
                :aid_type,
                :flow_type,
                :finance_type,
                :url,
                :lat,
                :lon,
                :transaction,
                :sectors_list,
                :project_locations

  validates :name,               :presence => true
  validates :id_in_organization, :presence => true

  def sectors=(value)
    @sectors = (value || '').split(',').map(&:to_i)
  end

  def subsectors=(value)
    @subsectors = (value || '').split(',').map(&:to_i)
  end

  def sectors
    (@sectors || []).map{|s| OpenAidRegister::SECTORS.select{|ss| ss.cartodb_id == s}.first}
  end

  def subsectors
    (@subsectors || []).map{|s| OpenAidRegister::SUBSECTORS.select{|ss| ss.cartodb_id == s}.first}
  end

  def budget_currency
    OpenAidRegister::CURRENCIES.select{|ss| ss.cartodb_id == @budget_currency_id}.first
  end

  def language
    OpenAidRegister::LANGUAGES.select{|ss| ss.cartodb_id == @language_id}.first
  end

  def organization_role
    OpenAidRegister::ORGANIZATION_ROLES.select{|ss| ss.cartodb_id == @organization_role_id}.first
  end

  def external_organizations
    InvolvedOrganizations.where(:project_id => id)
  end

  def sectors_list
    (subsectors || []).map{|s| ["#{OpenAidRegister::SECTORS.select{|ss| ss.cartodb_id == s.sector_id}.first.name}, #{s.name}}", "#{s.sector_id},#{s.cartodb_id}"]}
  end

  def project_locations
    @projects_locations ||= ProjectLocation.where(:project_id => id.to_i)
  end

  def locations_list
    project_locations.map {|point| ["(#{point.y}, #{point.x})", [point.y, point.x].join(',')] }
  end

  def lat=(value)
    attributes[:lat] = value
  end

  def lon=(value)
    attributes[:lon] = value
  end

  def sectors_list=(values)
    sectors    = []
    subsectors = []
    values.each do |value|
      sectors << value.split.first
      subsectors << value.split.last
    end
    @sectors    = sectors
    @subsectors = subsectors
  end

  def locations_list=(coordinates)
    return if coordinates.blank?

    self.project_locations = coordinates.map do |coordinate|
      next if coordinate.blank?

      lat, lon, location = */([^,]*),([^(]*)(?:\((.*)\))?/.match(coordinate).captures


      point = RGeo::GeoJSON.decode({:type        => 'Point', :coordinates => [lon, lat]}.to_json,
                                    :json_parser => :json,
                                    :geo_factory => ::RGeo::Cartesian.simple_factory(:srid => 4326)
                                  )

      ProjectLocation.new('project'  => self,
                          'location' => location,
                          'the_geom' => point)
    end.compact
  end

  def save
    if self.valid?
      super
      if @project_locations.present? && @project_locations.valid?
        @project_locations.save
      end
    end

    self
  end

  def self.for_user(user_id)
    query(<<-SQL)
      SELECT *
      FROM projects
      WHERE user_id = #{user_id};
    SQL
  end

  def user
    User.find_by_id(user_id)
  end

  def state
    if (start_date <=> Date.current) == 1
      return [1, 'Pipeline']
    elsif (end_date == nil) || (end_date <=> Date.current) == 1
      return [2, 'Implementing']
    else
      return [3, 'Completion']
    end
  end

  def coords
    project_locations.map{|point| point.to_coord} if project_locations.present?
  end

  def to_param
    cartodb_id
  end

  def as_json(options = {})
    options.merge({
      :cartodb_id => cartodb_id,
      :name       => name,
      :start_date => start_date,
      :end_date   => end_date,
      :coords     => coords,
      :state =>     state,
      :positions => coords
    })
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :get_user,    :only => :index
  before_filter :get_project, :only => [:show, :edit, :update, :destroy]

  layout :layout_if_ajax?

  def index
    @projects               = current_user.projects
    @organization           = current_user.organization || Organization.new
    @external_organizations = ExternalOrganization.grouped_by_project_id(@projects)
  end

  def show

  end

  def new
    @project            = Project.new(:user_id => current_user.id)
    @organization_roles = OpenAidRegister::ORGANIZATION_ROLES
    @languages          = OpenAidRegister::LANGUAGES
    @sectors            = OpenAidRegister::SECTORS
    @subsectors         = OpenAidRegister::SUBSECTORS
    @currencies         = OpenAidRegister::CURRENCIES
  end

  def create
    @project = Project.new(params[:project])

    if @project.save

      flash[:info] = :new_project

      redirect_to edit_project_path(@project)
    else
      render :new
    end
  end

  def edit
    @organization_roles  = OpenAidRegister::ORGANIZATION_ROLES
    @languages           = OpenAidRegister::LANGUAGES
    @sectors             = OpenAidRegister::SECTORS
    @subsectors          = OpenAidRegister::SUBSECTORS
    @currencies          = OpenAidRegister::CURRENCIES
    @collaboration_types = OpenAidRegister::COLLABORATION_TYPES
    @aid_types           = OpenAidRegister::AID_TYPES
    @flow_types          = OpenAidRegister::FLOW_TYPES
    @finance_types       = OpenAidRegister::FINANCE_TYPES
  end

  def update
    if @project.update_attributes(params[:project])
      flash[:info] = new_project_path
      redirect_to current_user
    else
      @collaboration_types = OpenAidRegister::COLLABORATION_TYPES
      @aid_types           = OpenAidRegister::AID_TYPES
      @flow_types          = OpenAidRegister::FLOW_TYPES
      @finance_types       = OpenAidRegister::FINANCE_TYPES
      render :edit
    end
  end

  def destroy
    @project.destroy

    render :nothing => true
  end

  private

  def get_project
    @project = Project.find_by_id(params[:id])
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper

  def field_translation(model, field_name)
    model_class = model.to_s.capitalize.constantize
    "#{model_class.model_name.human} #{model_class.human_attribute_name(field_name)}"
  end

  def json_for_new_project(new_project)
    new_project.to_json(:url => project_path(new_project), :auth_token => form_authenticity_token.inspect).html_safe
  end

end

app/views/projects/_advanced_project.html.erb
<script type="text/javascript">
  var current_user = {
        name: '<%= current_user.name %>',
        email: '<%= current_user.email %>'
      }
    , projects
    , project = <%= json_for_new_project(@project) %> || {};
</script>
<%= javascript_include_tag controller_name if request.xhr? %>
<%= stylesheet_link_tag controller_name, :media => 'all' if request.xhr? %>


<div class="form_inner">
  <section>
    <div>
      <h3 class="center upper"><span class="title_line"></span><%= t('projects.form_advanced.header.title') %><span class="title_line"></span></h3>
    </div>
  </section>

  <section class="header borders grey_section">
    <div class="center">
      <h4 class="dark"><%= t('projects.form_advanced.header.congrats') %></h4>
      <p class="margin5"><%= t('projects.form_advanced.header.basic_information') %></p>
    </div>
    <div class="center margin40">
      <%= link_to t('projects.form_advanced.header.complete_information'), "#complete_information", :class => "button round red uppercase continue_form" %>
      <span class="light">&nbsp;<%= t('projects.form_advanced.header.or') %>&nbsp;</span>
      <%= link_to t('projects.form_advanced.header.add_another_project'), new_project_path, :class => "button round light-grey uppercase new_project" %>
    </div>
  </section>

  <section>
    <%= render 'form_advanced' %>
  </section>
</div>

app/views/projects/_edit_project.html.erb
<%= link_to 'Basic data', '#' %>
<%= link_to 'Advanced data', '#' %>

<div class="basic">
  <%= render 'form_basic' %>
</div>

<div class="advanced">
  <%= render 'form_advanced' %>
</div>

app/views/projects/_form.html.erb
<%= form_for :project do |f| %>

  <div class="field name">
    <%= f.label :name, t('.name') %>
    <%= f.text_field :name %>
  </div>

  <div class="field id_in_organization">
    <%= f.label :id_in_organization, t('.id_in_organization') %>
    <%= f.text_field :id_in_organization %>
    <div class="hint">
      <p>Wadus</p>
    </div>
  </div>

  <div class="field description">
    <%= f.label :description, t('.description') %>
    <%= f.text_field :description %>
  </div>

  <div class="field organization_role">
    <%= f.label :organization_role, t('.organization_role') %>
    <%= f.select :organization_role, OrganizationRole.to_select_options %>
  </div>

  <div class="field language">
    <%= f.label :language, t('.language') %>
    <%= f.select :language, Language.to_select_options %>
  </div>

  <div class="field sector">
    <%= f.label :sector, t('.sector') %>

    <%= f.select :sector, Sector.to_select_options,       :include_blank => true %>
    <%= f.select :subsector, Subsector.to_select_options, :include_blank => true %>

    <%= f.button t('.add_button') %>
  </div>


  <div class="field start_date">
    <%= f.label :start_date, t('.start_end_date') %>
    <%= f.text_field :start_date %>
    <%= f.text_field :end_date %>
  </div>

  <div class="field budget">
    <%= f.label :budget, t('.budget') %>
    <%= f.text_field :budget %>
    <%= f.select :budget_currency, Currency.to_select_options %>
  </div>

  <div class="field contact_person">
    <%= f.label :contact_person, t('.contact_person') %>
    <%= f.text_field :contact_person %>
    <%= link_to t('.someone_different'), '#' %>
  </div>

  <div class="field url">
    <%= f.label :url, t('.url') %>
    <%= f.text_field :url %>
  </div>

<% end %>

app/views/projects/_form_advanced.html.erb
<%= form_for @project do |f| %>
  <div class="form_wrapper border">

    <div class="field long transactions">
      <label><%= t('.transactions.title') %></label>
      <div class="subform">
        <ul class="results">
          <li class="empty"><%= t('.transactions.no_records') %></li>
        </ul>
        <div class="form"></div>
        <%= link_to t('.transactions.add'), new_project_transaction_path(@project), :class => 'round grey button upper add_form margin10' %>
      </div>
    </div>

    <div class="field long involved-organizations margin50">
      <label><%= t('.involved_organizations.title') %></label>
      <div class="subform">
        <ul class="results">
          <li class="empty"><%= t('.involved_organizations.no_records') %></li>
        </ul>
        <div class="form"></div>
        <%= link_to t('.involved_organizations.add'), new_project_external_organization_path(@project), :class => 'round grey button upper add_form margin10' %>
      </div>
    </div>

    <div class="field long related_documents margin50">
      <label><%= t('.related_documents.title') %></label>
      <div class="subform">
        <ul class="results">
          <li class="empty"><%= t('.related_documents.no_records') %></li>
        </ul>
        <div class="form"></div>
        <%= link_to t('.related_documents.add'), new_project_document_path(@project), :class => 'round grey button upper add_form margin10' %>
      </div>
    </div>

    <div class="field long project-results margin50">
      <label><%= t('.project_results.title') %></label>
      <div class="subform">
        <ul class="results">
          <li class="empty"><%= t('.project_results.no_records') %></li>
        </ul>
        <div class="form"></div>
        <%= link_to t('.project_results.add'), new_project_project_result_path(@project), :class => 'round grey button upper add_form margin10' %>
      </div>
    </div>
  </div>


  <div class="form_wrapper margin50">
    <h3 class="upper"><%= t('.organization_information.title') %></h3>

    <div class="field collaboration_type long margin40">
      <%= f.label :collaboration_type, t('.organization_information.collaboration_type') %>
      <div class="select_wrapper med">
        <%= f.select :collaboration_type, to_select_options(@collaboration_types), { :include_blank => 'Not specified' } %>
      </div>
    </div>

    <div class="field tied_status long margin25">
      <fieldset>
        <legend><%= t('.organization_information.tied_status.legend') %></legend>

        <div class="choices">
          <div class="radio">
            <%= f.radio_button :tied_status, 1 %>
            <%= f.label :tied_status_1, t('.organization_information.tied_status.unknown') %>
          </div>

          <div class="radio">
            <%= f.radio_button :tied_status, 2 %>
            <%= f.label :tied_status_2, t('.organization_information.tied_status.partially_tied') %>
          </div>

          <div class="radio">
            <%= f.radio_button :tied_status, 3 %>
            <%= f.label :tied_status_3, t('.organization_information.tied_status.tied') %>
          </div>

          <div class="radio">
            <%= f.radio_button :tied_status, 4 %>
            <%= f.label :tied_status_4, t('.organization_information.tied_status.untied') %>
          </div>
        </div>
      </fieldset>
    </div>

    <div class="field aid_type long margin25">
      <%= f.label :aid_type, t('.organization_information.aid_type') %>
      <div class="select_wrapper med">
        <%= f.select :aid_type, to_select_options(@aid_types), { :include_blank => 'Not specified' } %>
      </div>
    </div>

    <div class="field flow_type long margin25">
      <%= f.label :flow_type, t('.organization_information.flow_type') %>
      <div class="select_wrapper med">
        <%= f.select :flow_type, to_select_options(@flow_types), { :include_blank => 'Not specified' } %>
      </div>
    </div>

    <div class="field finance_type long margin25">
      <%= f.label :finance_type, t('.organization_information.finance_type') %>
      <div class="select_wrapper med">
        <%= f.select :finance_type, to_select_options(@finance_types), { :include_blank => 'Not specified'} %>
      </div>
    </div>

    <div class="field long margin50">
      <%= link_to t('.cancel'), '#', :class => "margin15 left cancel" %>
      <%= f.submit t('.save_changes'), :class => "button round red bigger right" %>
    </div>
  </div>
<% end %>

app/views/projects/_form_basic.html.erb
  <%= form_for @project, :html => {:class => 'new_basic'} do |f| %>

    <%= f.hidden_field :user_id %>

    <div class="form_wrapper">
      <div class="field name long">
        <div class="block">
          <%= f.label :name, t('.name'), :class => "with_hint" %>
          <span class="hint"
            data-title="<%= t('projects.help.project_name.title') %>"
            data-description="<%= t('projects.help.project_name.desc') %>"
            data-url="<%= t('projects.help.project_name.url') %>"
            data-examples="<%= t('projects.help.project_name.examples') %>"></span>
        </div>
        <%= f.text_field :name, :class => "long" %>
      </div>

      <div class="field id_in_organization long margin20">
        <div class="block">
          <%= f.label :id_in_organization, t('.id_in_organization'), :class => "with_hint" %>
          <span class="hint"
            data-title="<%= t('projects.help.project_id.title') %>"
            data-description="<%= t('projects.help.project_id.desc') %>"
            data-url="<%= t('projects.help.project_id.url') %>"
            data-examples="<%= t('projects.help.project_id.examples') %>"></span>
        </div>
        <%= f.text_field :id_in_organization, :class => "short" %>
      </div>

      <div class="field description long margin20">
        <%= f.label :description, t('.description') %>
        <%= f.text_area :description %>
      </div>

      <div class="field organization_role med margin20">
        <%= f.label :organization_role, t('.organization_role') %>
        <div class="select_wrapper">
          <%= f.select :organization_role, to_select_options(@organization_roles), { :include_blank => 'Not specified' }, { 'data-placeholder' => "Not defined..." } %>
        </div>
      </div>

      <div class="field language margin short margin20">
        <%= f.label :language, t('.language') %>
        <div class="select_wrapper">
          <%= f.select :language, to_select_options(@languages) %>
        </div>
      </div>

      <div class="field sector long margin20">
        <%= f.label :sector, t('.sector') %>
        <div class="grey_wrapper">
          <div class="select_wrapper">
            <div class="column">
              <%= select_tag :sector, options_from_collection_for_select(@sectors, 'id', 'name'),       { :include_blank => 'Not specified' , 'data-placeholder' => "Sector..." } %>
              <span class="sptor"></span>
            </div>
            <div class="column">
              <%= select_tag :subsector, options_from_collection_for_select_with_attributes(@subsectors, 'cartodb_id', 'name', :'data-sector-id' => 'sector_id'), { :include_blank => 'Not specified', 'data-placeholder' => "Subsector..." } %>
            </div>
          </div>
          <%= f.button t('.add_button'), :class => "round grey right add" %>
        </div>
        <%= f.select :sectors_list, @project.sectors_list, {:include_blank => false}, { :multiple => true, :id => 'sectors_list' } %>
      </div>

      <div class="field start_date long margin20">
        <%= f.label(:start_date) do %>
          <%= t('.start_end_date') %> <em class="light">(MM/DD/YYYY)</em>
        <% end %>

        <div class="select_wrapper">
          <div class="column">
            <%= f.text_field :start_date, :class => 'short inner_input' %>
            <span class="sptor"></span>
          </div>
          <div class="column">
            <%= f.text_field :end_date, :class => 'short inner_input' %>
          </div>
        </div>
      </div>

      <div class="field budget short margin20">
        <%= f.label :budget, t('.budget') %>
        <div class="select_wrapper">
          <div class="column">
            <%= f.text_field :budget, :class => 'tiny inner_input' %>
            <span class="sptor"></span>
          </div>
          <div class="column">
            <%= f.select :budget_currency, to_select_options(@currencies), :style => "width:30px" %>
          </div>
        </div>
      </div>
    </div>

    <div class="field locations margin20">
      <div class="form_wrapper">
        <%= f.label :locations, t('.locations') %>
        <p class="small light right margin5"><%= t('.location.desc') %></p>
      </div>
      <div class="form">
        <input id="geocomplete" type="text" placeholder="<%= t('.location.geocomplete') %>" />
        <input type="submit" value=""/>
      </div>
      <div id="locations_map"></div>
      <input type="hidden" id="location" />
      <%= f.select :locations_list, @project.locations_list, {:include_blank => false}, { :multiple => true, :id => 'locations_list' } %>
    </div>

    <div class="form_wrapper">
      <div class="field url long margin20">
        <%= f.label :url, t('.url') %>
        <%= f.text_field :url, :class => "med" %>
      </div>

      <div class="field contact_person long margin20">
        <div class="block">
          <%= f.label :contact_person, t('.contact_person.title'), :class => "with_hint" %>
          <p class="small light right margin5 you"><%= link_to t('.contact_person.question'), '#you?' %></p>
        </div>

        <div class="select_wrapper">
          <span class="light"><%= t('.you') %></span>
          <%= link_to t('.someone_different'), '#change', :class => "different right" %>
        </div>

        <div class="contact_form">
          <div class="field">
            <label><%= t('.contact_person.name') %></label>
            <input type="text" id="contact_person_name" value="<%= current_user.name %>" />
          </div>
          <div class="field margin">
            <label><%= t('.contact_person.email') %></label>
            <input type="text" id="contact_person_email" value="<%= current_user.email %>" />
          </div>
        </div>
      </div>

      <div class="field long margin40">
        <%= link_to t('.cancel'), '#', :class => "margin15 left cancel" %>
        <%= f.submit t('.save'), :class => "button round red right bigger" %>
      </div>
    </div>
  <% end %>

app/views/projects/edit.html.erb
<% if flash[:info] == :new_project %>
  <%= render 'advanced_project' %>
<% else %>
  <%= render 'edit_project' %>
<% end %>

app/views/projects/index.csv.erb
<% fields = %w(
cartodb_id
user_id
name
id_in_organization
description
organization_role_id
language_id
sectors
subsectors
start_date
end_date
budget
budget_currency_id
contact_person
collaboration_type
tied_status
aid_type
flow_type
finance_type
url
coords
transaction
) %><%= fields.join(',') %>
<% @projects.each do |project| %>
  <%= fields.map{|f| project.send(f)}.join(',') %>
<% end %>

app/views/projects/index.html.erb
<% content_for(:page_title) do %>OpenAidRegister<% end %>

<script type="text/javascript">
  var projects = <%= @projects.to_json.html_safe %>
    , current_user;
</script>

<div id="embed_map">
  <div class="map"></div>
  <div id="zoom"><a class="zoom_in">+</a><a class="zoom_out">-</a></div>
</div>

app/views/projects/index.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<iati-activities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" generated-datetime="<%= Time.zone.now.to_datetime %>" version="1.01">

<% @projects.each do |project| %>
    <iati-activity last-updated-datetime="<%= project.updated_at %>" default-currency="<%= project.budget_currency.try(:name) %>" xml:lang="<%= project.language.try(:name) %>">

      <reporting-org type="<%= @organization.type_id %>" ref="<%= @organization.government_id %>"><%= @organization.try(:name) %></reporting-org>
      <iati-identifier><%= [@organization.country, @organization.government_id, project.id_in_organization].compact.join('-') %></iati-identifier>

      <title><%= project.try(:name) %></title>

      <% if project.description.present? %>
        <description><%= project.description %></description>
      <% end %>

      <% if project.start_date.present? %>
        <activity-status code="<%= project.state.first %>"><%= project.state.last %></activity-status>
        <activity-date type="start-actual" iso-date="<%= l project.start_date, :format => :dashed %>">
          <%= l project.start_date, :format => :dashed %>
        </activity-date>
      <% end %>

      <% if project.end_date.present? %>
        <activity-date type="end-planned" iso-date="<%= l project.end_date, :format => :dashed %>">
          <%= l project.end_date, :format => :dashed %>
        </activity-date>
      <% end %>

      <participating-org role="<%= project.organization_role.try(:name) %>" type="<%= @organization.type_id %>" ref="<%= [@organization.country, @organization.government_id].compact.join('-') %>">
        <%= @organization.try(:name) %>
      </participating-org>

      <% @external_organizations[project.id].each do |external_organization| %>
        <participating-org role="<%= external_organization.role.name %>" type="" ref="">
          <%= external_organization.name %>
        </participating-org>
      <% end %>

      <% @related_documentation[project.id].each do |related_document| %>
        <document-link url="<%= related_document.file.url %>" format="" xml:lang="">
          <category code="<%= related_document.type.name %>"></category>
        </document-link>
      <% end %>

      <% if project.url.present? %>
        <activity-website><%= project.url %></activity-website>
      <% end %>

      <% @sectors[project.id].each do |sector| %>
        <sector vocabulary="DAC" code="<%= sector.code %>">
          <%= sector.name %>
        </sector>
      <% end %>

      <% if project.id_in_organization.present? %>
        <related-activity type="1" ref="<%= project.id_in_organization %>"></related-activity>
      <% end %>

      <% if false %>
        <% if project.other_iati_project_identifier.blank? %>
          <other-identifier owner-ref="" owner-name=""><%= project.other_iati_project_identifier %></other-identifier>
        <% end %>
      <% end %>

  <% if project.budget.preset? %>
    <budget>
      <value currency="<%= project.budget_currency.name %>" value-date="<%= format_date_dash(project.start_date) %>"><%= project.budget.to_i %></value>
    </budget>
  <% end %>

  <% if false %>
  <% @geo_projects.each do |geo_project| %>
    <% if geo_project[:project_id] == project.cartodb_id %>
      <% if geo_project[:level_detail] == "country"%>
        <recipient-country code="<%= geo_project[:country] %>">
          <%= geo_project[:country_extended] %>
        </recipient-country>

      <% elsif geo_project[:level_detail] == "region" %>
        <recipient-country code="<%= geo_project[:country] %>">
          <%= geo_project[:country_extended] %>
        </recipient-country>
        <location><location-type code="ADM1"><%= geo_project[:adm1] %></location-type></location>

      <% elsif geo_project[:level_detail] == "city" %>
        <recipient-country code="<%= geo_project[:country] %>">
          <%= geo_project[:country_extended] %>
        </recipient-country>

        <location>
          <location-type code="ADM1"><%= geo_project[:adm1] %></location-type>
          <location-type code="ADM2"><%= geo_project[:adm2] %></location-type>
        </location>

      <% else %>
        <location>
          <coordinates latitude="<%= geo_project[:latlng].split(/ /)[1] %>" longitude="<%= geo_project[:latlng].split(/ /)[0] %>" precision="2"/>
        </location>
      <% end %>
    <% end %>
  <% end %>

  <% if project.result_title.present? %>
    <result type="output">
      <title><%=project.result_title %></title>
      <% if !project.result_description.blank? %>
        <description><%= project.result_description %></description>
      <% end %>
    </result>
  <% end %>

  <% if !project.contact_name.blank? || !project.contact_email.blank? %>
    <contact-info>
      <% if !project.contact_name.blank? %>
        <person-name><%= project.contact_name %></person-name>
      <% end %>

      <% if !project.contact_email.blank? %>
        <email><%= project.contact_email %></email>
      <% end %>
    </contact-info>
  <% end %>

  <% @transaction_list.each do |transaction| -%>
    <% if transaction[:project_id] == project.cartodb_id %>
      <transaction>
        <transaction-type code="<%=transaction[:transaction_type]%>">
          <%=transaction_type_by_name (transaction[:transaction_type]) %>
        </transaction-type>

        <value currency="<%= currency_by_name (transaction[:transaction_currency]) %>" value-date="<%= format_date_dash(transaction[:transaction_date]) %>">
          <%= transaction[:transaction_value].to_i %>
        </value>

        <transaction-date iso-date="<%= format_date_dash(transaction[:transaction_date]) %>"/>
        <% if transaction[:provider_id].present? || transaction[:provider_activity_id].present? || transaction[:provider_name].present?  %>
          <provider-org ref="<%= transaction[:provider_id] %>" provider-activity-id="<%= transaction[:provider_activity_id] %>">
            <%= transaction[:provider_name] %>
          </provider-org>
        <% end %>

        <% if transaction[:receiver_id].present? || transaction[:receiver_activity_id].present? || transaction[:receiver_name].present?  %>
          <receiver-org ref="<%= transaction[:receiver_id] %>" receiver-activity-id="<%= transaction[:receiver_activity_id] %>">
            <%= transaction[:receiver_name] %>
          </receiver-org>
        <% end %>

        <% if transaction[:transaction_description].present? %>
          <description xml:lang="en"><%= transaction[:transaction_description] %></description>
        <% end %>
      </transaction>
    <% end -%>
  <% end -%>

  <% if !project.collaboration_type.blank? %>
    <collaboration-type code="<%= project.collaboration_type %>">
      <%= collaboration_type_by_id(project.collaboration_type) %>
    </collaboration-type>
  <% end %>

  <% if !project.aid_type.blank? %>
    <default-aid-type code="<%= project.aid_type %>">
      <%= aid_type_by_id (project.aid_type) %>
    </default-aid-type>
  <% end %>

  <% if !project.tied_status.blank? %>
    <default-tied-status code="<%= project.tied_status %>">
      <%= tied_status_by_id (project.tied_status) %>
    </default-tied-status>
  <% end %>

  <% if !project.flow_type.blank? %>
    <default-flow-type code="<%= project.flow_type %>">
      <%= flow_type_by_id (project.flow_type) %>
    </default-flow-type>
  <% end %>

  <% if !project.finance_type.blank? %>
    <default-finance-type code="<%= project.finance_type %>">
      <%= finance_type_by_id (project.finance_type) %>
    </default-finance-type>
  <% end %>

    <% end %>
</iati-activity>

  <% end %>
</iati-activities>

app/views/projects/new.html.erb
<script type="text/javascript">
  var current_user = {
        name: '<%= current_user.name %>',
        email: '<%= current_user.email %>'
      }
    , projects
    , project;
</script>
<%= javascript_include_tag controller_name if request.xhr? %>
<%= stylesheet_link_tag controller_name, :media => 'all' if request.xhr? %>

<div class="form_inner">
  <section>
    <div>
      <h3 class="center upper"><span class="title_line"></span><%= t('.title') %><span class="title_line"></span></h3>
    </div>
  </section>

  <section class="grey_section">
    <div class="center">
      <h4 class="dark"><%= t('.info.title') %></h4>
      <p class="description margin5"><%= t('.info.description') %></p>
    </div>
  </section>

  <section>
    <%= render 'form_basic' %>
  </section>
</div>