config/routes.rb
Openaidregister::Application.routes.draw do

  resources :users do
    resources :projects
    resources :organizations do
      resources :budgets
      resources :documents
      resources :administrators
    end
  end

  resources :sessions

  resources :projects do
    resources :transactions
    resources :external_organizations
    resources :documents
    resources :project_results
  end

  root :to     => 'home#index'
  get '/faq'   => 'home#faq'
  get '/about' => 'home#about'
  get '/terms' => 'home#terms'

end

app/views/layouts/_footer.html.erb
<footer>
  <div class="inner">
    <section class="borders padding">
      <div class="padding">
        <p class="left lighter"><%= t('footer.info') %></p>
        <span class="right">
          <%= link_to image_tag("logos/ny_law_school.png", :border=>0), "http://www.nyls.edu/", :target => "_blank" %>
          <%= link_to image_tag("logos/iati.png", :border=>0), "http://www.aidtransparency.net/", :target => "_blank" %>
        </span>
      </div>
      <nav class="margin50">
        <%= link_to t('footer.nav.contact'), "mailto:contact@openaidregister.org" %>
        &#8226;
        <%= link_to t('footer.nav.faq'), faq_path %>
        &#8226;
        <%= link_to t('footer.nav.blog'), 'http://blog.openaidregister.org' %>
        &#8226;
        <%= link_to t('footer.nav.about'), about_path %>
        &#8226;
        <%= link_to t('footer.nav.terms'), terms_path %>
      </nav>
    </section>
  </div>
</footer>

app/views/layouts/_sessions_footer.html.erb
<footer >
  <div class="inner">
    <section class="padding">
      <div class="center margin">
        <%= link_to image_tag("logos/ny_law_school.png", :border=>0), "http://www.nyls.edu/", :target => "_blank" %>
        <%= link_to image_tag("logos/iati.png", :border=>0), "http://www.aidtransparency.net/", :target => "_blank", :class => "margin" %>
      </div>
      <nav class="margin40 center">
        <%= link_to t('footer.nav.contact'), "mailto:contact@openaidregister.org" %>
        &#8226;
        <%= link_to t('footer.nav.faq'), faq_path %>
        &#8226;
        <%= link_to t('footer.nav.blog'), 'http://blog.openaidregister.org' %>
        &#8226;
        <%= link_to t('footer.nav.about'), about_path %>
        &#8226;
        <%= link_to t('footer.nav.terms'), terms_path %>
      </nav>
    </section>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <link rel="shortcut icon" href="/assets/favicon.ico" type="image/x-icon">
  <title><%= yield :page_title %></title>
  <meta name="description" content="">
  <meta name = "viewport" content = "width = 1020">
  <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Droid+Sans:400,700|Open+Sans:400,700", :media => 'all' %>
  <%= stylesheet_link_tag "https://www.google.com/cse/style/look/default.css", :media => 'all' %>
  <%= stylesheet_link_tag :application,    :media => 'all' %>
  <%= stylesheet_link_tag controller_name, :media => 'all' %>
  <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?sensor=false&libraries=places' %>
  <%= javascript_include_tag :application %>
  <%= javascript_include_tag controller_name %>
  <%= yield :extra_assets %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</body>
</html>